services:
  - type: web
    name: craft-connect-backend
    env: python
    plan: free
    rootDir: backend
    buildCommand: "pip install -r requirements.txt && python manage.py collectstatic --noinput && python manage.py migrate"
    startCommand: "gunicorn craft_connect.wsgi:application"
    envVars:
      - key: DJANGO_DEBUG
        value: "False"
      - key: PYTHON_VERSION
        value: "3.11.0"
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_ALLOWED_HOSTS
        value: "*"
      - key: DATABASE_URL
        sync: false
      - key: CORS_ALLOW_ALL
        value: "True"
      - key: RAZORPAY_KEY_ID
        value: "rzp_test_TUR8r68CSqlefv"
      - key: RAZORPAY_KEY_SECRET
        value: "rQ9fke7j3KC3qz3uT0ben1H3"
