# Generated by Django 5.2.12 on 2026-04-02 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_published',
            field=models.BooleanField(default=False, help_text='Draft until explicitly published by the artisan.'),
        ),
    ]
