# Generated by Django 5.2.12 on 2026-04-01 14:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(choices=[('product', 'Product'), ('course', 'Course')], max_length=10)),
                ('object_id', models.PositiveIntegerField()),
                ('action', models.CharField(choices=[('view', 'Viewed'), ('purchase', 'Purchased'), ('enroll', 'Enrolled'), ('wishlist', 'Wishlisted')], max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'User Activities',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', 'content_type'], name='recommendat_user_id_3801f6_idx'), models.Index(fields=['content_type', 'object_id'], name='recommendat_content_84f767_idx')],
            },
        ),
    ]
